<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Todays Alerts</name>
   <tag></tag>
   <elementGuidId>c32c77ea-356d-44b5-ac35-22cf5e83c154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.TextValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>802ddea0-9d20-4807-b404-3fb944ab8a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextValue</value>
      <webElementGuid>6e0d880d-aa3e-42e4-9eae-9747a467128b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today's Alerts</value>
      <webElementGuid>03c40e1e-3e1d-42e2-8349-6f768230582a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/main[@class=&quot;mainDiv&quot;]/div[@class=&quot;mainContent&quot;]/div[@class=&quot;MainContentMargin&quot;]/div[@class=&quot;dashboardScroll&quot;]/div[@class=&quot;RowClass&quot;]/div[@class=&quot;grid-container grid-container--fit&quot;]/div[@class=&quot;KPI_Margin&quot;]/div[@class=&quot;topKpiCard&quot;]/div[@class=&quot;AlertsCount custom-cursor-on-hover&quot;]/div[@class=&quot;dashboard-card-content&quot;]/div[@class=&quot;dashbord-card-txt&quot;]/div[2]/p[@class=&quot;TextValue&quot;]</value>
      <webElementGuid>2f551fea-177f-404a-9c1b-ce039167e548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div[3]/div/div/div[2]/div/div/div/div[2]/div[2]/p</value>
      <webElementGuid>37e5af96-fe95-4834-8354-848959759c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Health'])[1]/following::p[4]</value>
      <webElementGuid>680fe31e-bdf7-4252-bc1d-b965a6be0f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Devendra Patil'])[2]/following::p[4]</value>
      <webElementGuid>19e8661e-6b9e-4dff-81fd-1f6ce8f73e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::p[13]</value>
      <webElementGuid>b18c77e4-a213-4fdc-b533-4d057f37a3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/preceding::p[13]</value>
      <webElementGuid>8722e052-b31e-447e-a996-35cf008563b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/p</value>
      <webElementGuid>060101f1-20a4-4085-a170-ee79c8c8d204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot;Today&quot; , &quot;'&quot; , &quot;s Alerts&quot;) or . = concat(&quot;Today&quot; , &quot;'&quot; , &quot;s Alerts&quot;))]</value>
      <webElementGuid>65357b90-091c-4c9e-93ad-0de362a801e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
