<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>c44f2845-c549-42cf-a608-d9405de110ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ResetPasswordButton.w25dot75rem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7abf30d8-db0c-4515-b2f5-dd4dee2f09b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ResetPasswordButton w25dot75rem</value>
      <webElementGuid>14452a3c-8e9d-4f77-855c-089cbfe96007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>dd793b53-7806-438a-abb4-05c691b6a8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid forgot-pass-container&quot;]/div[@class=&quot;row forgot-pass-row&quot;]/div[@class=&quot;col-lg-6 ContentForm col-md-6 col-sm-12 col-xs-12 login-col-2&quot;]/div[@class=&quot;WhiteFormSignIn&quot;]/div[@class=&quot;Content&quot;]/button[@class=&quot;ResetPasswordButton w25dot75rem&quot;]</value>
      <webElementGuid>a20d1c82-6dae-43ef-9cda-8a18c41ecf84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/button</value>
      <webElementGuid>54aff17e-0c1b-4432-8d09-d92a57c7c4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>1fa58c60-d06f-4eea-9387-7cd1aca01cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email ID'])[1]/following::button[1]</value>
      <webElementGuid>60626382-118b-41fe-a385-66bb125c9ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='agreement'])[1]/preceding::button[1]</value>
      <webElementGuid>2a609e59-a6ce-43ef-8754-5e0855fa07a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0fb296d2-c7c5-4d47-9b56-5dce4de7b24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>20d8f882-8de5-454c-8d40-67c97b4bd9de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
